### ISSUE TITLE
cant use scala to write kafka streams

### ISSUE THREAD

**Issue by LinMingQiang** [aseigneurin/kafka-streams-scala#2]
why i cant use scala to write kafka streams
scala version 2.10
kafka version 0.10.0
Cannot compile ：
val builder = new KStreamBuilder();
val source = builder.stream[String,String](new String("topics"));
source.map(value => value.toLowerCase)

**Comment by aseigneurin** [comment]
This cannot work with Scala 2.10 because it requires Scala lambdas to be converted to Java 8 lambas.

Use Scala 2.11 or Scala 2.12 instead.
